import { Banner } from "../types";

export const Banners: Banner[] = [
    {
        title: "Hydropump Is Live",
        description: "Hydropump is live on Hydrex",
        mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/hydropump-mobile.png",
        desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/hydropump-desktop.png",
        internalUrl: "/hydropump",
        isLive: true,
        placementNumber: 1,
    },
    {
        title: "Hydrex Governance",
        description: "Governance on Hydrex",
        mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/governance-mobile.png",
        desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/governance-desktop.png",
        externalUrl: "https://governance.hydrex.fi",
        isLive: true,
        placementNumber: 2,
    },
    {
        title: "Hydrex Perps",
        description: "Trade Perps on Hydrex",
        mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/perps-mobile.png",
        desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/perps-desktop.png",
        externalUrl: "https://perps.hydrex.fi",
        isLive: true,
        placementNumber: 3,
    },
    // {
    //     title: "Bankr Skills Live",
    //     description: "Hydrex Skills Live on Bankr",
    //     mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/bankr-mobile.png",
    //     desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/bankr-desktop.png",
    //     internalUrl: "/pools",
    //     isLive: true,
    //     placementNumber: 3,
    // },
    // {
    //     title: "Hydrex Academy",
    //     description: "Learn DeFi with the Hydrex Academy.",
    //     mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/academy-mobile.png",
    //     desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/academy-desktop.png",
    //     externalUrl: "https://academy.hydrex.fi",
    //     isLive: true,
    //     placementNumber: 3,
    // },
    // {
    //     title: "Liquidity Provisioning",
    //     description: "Work with us to provide liquidity.",
    //     mobileBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/liquidity-mobile.png",
    //     desktopBannerImage: "https://raw.githubusercontent.com/hydrexfi/hydrex-lists/staging/assets/banners/liquidity-desktop.png",
    //     externalUrl: "https://docs.google.com/forms/d/e/1FAIpQLScR82qfEFmSysrbrSESiJr9wM1ZAWUVnYJIouS2xBio5iH0zg/viewform?usp=sharing&ouid=105771834148534931546",
    //     isLive: true,
    //     placementNumber: 3,
    // },
];
